project_name: gitwrk
before:
  hooks:
    - go mod download
    - go test ./...

builds:
- env:
    - CGO_ENABLED=0

  main: ./cmd/main.go
  binary: gitwrk

  goos:
    - linux
    - darwin
    - windows

  ignore:
    - goos: darwin
      goarch: 386
    - goos: linux
      goarch: 386

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
    - '^refactor:'

release:
  github:
    owner: unravela
    name: gitwrk
  name_template: "{{.ProjectName}}-v{{.Version}}"

scoop:
  bucket:
    owner: unravela
    name: scoop-bucket
  homepage: https://github.com/unravela/gitwrk
  description: A small CLI tool that helps you with monthly reports by extracting working hours directly from git repository.
  license: Apache 2.0

brews:
  - name: gitwrk
    github:
      owner: unravela
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/unravela/gitwrk
    description: A small CLI tool that helps you with monthly reports by extracting working hours directly from git repository.

nfpms:
  -
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: 64-bit
      386: 32-bit

    formats:
      - deb
      - rpm

    scripts:
      postinstall: "scripts/postinstall.sh"

    epoch: 1
    release: 1
    vendor: unravela.io
    homepage: https://github.com/unravela
    maintainer: zdenko vrabel (zdenko.vrabel@unravela.io)
    description: A small CLI tool that helps you with monthly reports by extracting working hours directly from git repository.
    license: Apache 2.0

snapcrafts:
  -
    name: gitwrk
    publish: true
    summary: A small CLI tool that helps you with monthly reports by extracting working hours directly from git repository.
    description:  |
      **GitWrk** is a small commandline application that helps you with monthly reports by extracting working hours directly from git repository.

      **Motivation**
      As freelance developers or outsourced developers, we need to report our work hours. For years we used tools like Jira or some weird 3rd party tools for logging our hours. Having 3 different tools for reporting our work is always exhausting and error prone. Because we love transparency, we want to provide good data.

    license: Apache 2.0