project_name: gitwrk
before:
  hooks:
    - go mod download

builds:
- env:
    - CGO_ENABLED=0

  goos:
    - linux
    - darwin
    - windows

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  github:
    owner: unravela
    name: gitwrk
  name_template: "{{.ProjectName}}-v{{.Version}}"

scoop:
  bucket:
    owner: unravela
    name: scoop-bucket
  homepage: https://github.com/unravela/gitwrk
  description: A small CLI tool that helps you with monthly reports by extracting working hours directly from git repository.
  license: Apache 2.0